import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname),dir=resolve(root,'data','backtest');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function getJSON(url){let last;for(let i=0;i<4;i++){try{const r=await fetch(url,{headers:{'user-agent':'weatherbot-research/1.0'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`${r.status}`);return r.json()}catch(e){last=e;await sleep(600*(i+1))}}throw last}
const finite=a=>(a||[]).map(Number).filter(Number.isFinite),mean=a=>a.reduce((s,x)=>s+x,0)/a.length,median=a=>{const b=[...a].sort((x,y)=>x-y);return b.length?b[Math.floor(b.length/2)]:null};
function bucket(label){if(typeof label!=='string')return null;const f=/°F|F\b/.test(label),nums=(label.match(/\d+(?:\.\d+)?/g)||[]).map(Number),toC=x=>f?(x-32)*5/9:x;if(!nums.length)return null;if(/below/i.test(label))return{low:-Infinity,high:toC(nums[0]+.5),unit:f?'F':'C'};if(/higher/i.test(label))return{low:toC(nums[0]-.5),high:Infinity,unit:f?'F':'C'};if(nums.length>=2)return{low:toC(nums[0]-.5),high:toC(nums[1]+.5),unit:f?'F':'C'};return{low:toC(nums[0]-.5),high:toC(nums[0]+.5),unit:f?'F':'C'}}
const rangeCheck=bucket('98-99°F');if(!rangeCheck||rangeCheck.low<35||rangeCheck.high>38)throw new Error('temperature bucket parser self-check failed');
const erf=x=>{const s=Math.sign(x),a=Math.abs(x),t=1/(1+.3275911*a),y=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-a*a);return s*y};
const cdf=x=>(1+erf(x/Math.SQRT2))/2;
function winnerProbability(bounds,centre,sigma){const lo=Number.isFinite(bounds.low)?cdf((bounds.low-centre)/sigma):0,hi=Number.isFinite(bounds.high)?cdf((bounds.high-centre)/sigma):1;return Math.max(1e-6,hi-lo)}
function fit(rows,lead){const usable=rows.filter(x=>Number.isFinite(x.features?.[lead]?.centre_c)&&Number.isFinite(x.winner_mid_c)),res=usable.map(x=>x.winner_mid_c-x.features[lead].centre_c),bias=median(res),mad=median(res.map(x=>Math.abs(x-bias))),sigma=Math.max(.35,1.4826*mad);return{n:usable.length,bias_c:bias,sigma_c:sigma,mae_c:mean(res.map(Math.abs)),rmse_c:Math.sqrt(mean(res.map(x=>x*x)))}}
function score(rows,lead,model){const losses=[];for(const x of rows){const centre=x.features?.[lead]?.centre_c;if(!Number.isFinite(centre)||!x.bounds)continue;losses.push(-Math.log(winnerProbability(x.bounds,centre+model.bias_c,model.sigma_c)))}return{n:losses.length,mean_winner_log_loss:losses.length?mean(losses):null}}
async function main(){await mkdir(dir,{recursive:true});const source=JSON.parse(await readFile(resolve(dir,'market-history.json'),'utf8')),rows=[];for(let i=0;i<source.length;i++){const row=source[i],bounds=bucket(row.winner?.bucket);if(!row.station||!row.target_date||!bounds)continue;try{const q=new URLSearchParams({latitude:String(row.station.latitude),longitude:String(row.station.longitude),start_date:row.target_date,end_date:row.target_date,hourly:'temperature_2m_previous_day0,temperature_2m_previous_day1,temperature_2m_previous_day2',models:'ecmwf_ifs025,gfs_seamless',timezone:row.station.timezone});const x=await getJSON(`https://previous-runs-api.open-meteo.com/v1/forecast?${q}`),features={};for(let lead=0;lead<=2;lead++){const ep=finite(x.hourly?.[`temperature_2m_previous_day${lead}_ecmwf_ifs025`]),gp=finite(x.hourly?.[`temperature_2m_previous_day${lead}_gfs_seamless`]);if(ep.length&&gp.length){const e=Math.max(...ep),g=Math.max(...gp);features[`day${lead}`]={ecmwf_peak_c:e,gfs_peak_c:g,centre_c:(e+g)/2,spread_c:Math.abs(e-g)}}}const winnerMid=Number.isFinite(bounds.low)&&Number.isFinite(bounds.high)?(bounds.low+bounds.high)/2:null;rows.push({event_id:row.event_id,title:row.title,target_date:row.target_date,station:row.station.icao,winner_bucket:row.winner.bucket,bounds,winner_mid_c:winnerMid,features});process.stdout.write(`\r${i+1}/${source.length}`);await sleep(100)}catch(error){rows.push({event_id:row.event_id,title:row.title,error:error.message})}}
 const dated=rows.filter(x=>x.winner_mid_c!==null).sort((a,b)=>a.target_date.localeCompare(b.target_date)),split=Math.max(1,Math.floor(dated.length*.7)),train=dated.slice(0,split),test=dated.slice(split),models={};for(const lead of ['day0','day1','day2']){const fitted=fit(train,lead);models[lead]={...fitted,holdout:score(test,lead,fitted),baseline_holdout:score(test,lead,{bias_c:0,sigma_c:1.25})}}
 const dates=[...new Set(dated.map(x=>x.target_date))];const report={generated_at:new Date().toISOString(),warning:'research only; no live calibration unlock',events:rows.length,usable_non_tail_events:dated.length,independent_target_dates:dates.length,split:'chronological 70/30 by event rows',models,auto_apply:false,reason:dates.length<30?'fewer than 30 independent target dates':'requires explicit review'};await writeFile(resolve(dir,'weather-training.json'),JSON.stringify(rows,null,2));await writeFile(resolve(dir,'calibration-report.json'),JSON.stringify(report,null,2));process.stdout.write(`\nTraining report saved; independent dates=${dates.length}.\n`)}
main().catch(e=>{console.error(e);process.exitCode=1});
